# Generated by Django 4.0.4 on 2023-09-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_kyc_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
