# Generated by Django 4.0.4 on 2023-10-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_kyc_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='account',
            name='review',
            field=models.CharField(blank=True, default='Review', max_length=100, null=True),
        ),
    ]
